<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxfubcx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxfubcx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXxfubcx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXxfubcx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXxfubcx\appProdProjectContainer([
    'container.build_hash' => 'Xxfubcx',
    'container.build_id' => '39f8dbb8',
    'container.build_time' => 1660052708,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxfubcx');
